"""
Pydantic Schemas for LLM-Generated Content

These schemas define the structure of content generated by the LLM.
They can be converted to game templates for use in the world.
"""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class ExitDirection(str, Enum):
    """Valid exit directions."""

    NORTH = "north"
    SOUTH = "south"
    EAST = "east"
    WEST = "west"
    UP = "up"
    DOWN = "down"


class SectorType(str, Enum):
    """Types of room sectors."""

    INSIDE = "inside"
    CITY = "city"
    FIELD = "field"
    FOREST = "forest"
    HILLS = "hills"
    MOUNTAIN = "mountain"
    WATER_SWIM = "water_swim"
    WATER_NO_SWIM = "water_no_swim"
    UNDERWATER = "underwater"
    AIR = "air"
    DESERT = "desert"
    CAVE = "cave"


class RoomExit(BaseModel):
    """An exit from a room."""

    direction: ExitDirection = Field(description="Direction of the exit")
    description: str = Field(description="Brief description of what's in that direction")
    difficulty: Optional[str] = Field(
        default=None, description="Any difficulty or requirement to use this exit"
    )


class GeneratedRoom(BaseModel):
    """Schema for LLM-generated room content."""

    name: str = Field(
        min_length=3,
        max_length=60,
        description="Short name for the room (shown in room header)",
    )
    short_description: str = Field(
        min_length=10,
        max_length=100,
        description="One-line description shown when moving through",
    )
    long_description: str = Field(
        min_length=50,
        max_length=1000,
        description="Full description shown when looking at the room",
    )
    sector_type: SectorType = Field(
        default=SectorType.INSIDE, description="Type of terrain/environment"
    )
    exits: list[RoomExit] = Field(
        default_factory=list,
        min_length=1,
        max_length=6,
        description="Available exits from this room",
    )
    ambient_messages: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Random ambient messages that can appear in the room",
    )
    atmosphere: Optional[str] = Field(
        default=None, description="General atmosphere/mood of the room"
    )
    notable_features: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Notable features players might want to examine",
    )


class CombatStyle(str, Enum):
    """Combat behavior styles for mobs."""

    AGGRESSIVE = "aggressive"
    DEFENSIVE = "defensive"
    TACTICAL = "tactical"
    BERSERKER = "berserker"
    COWARDLY = "cowardly"
    RANGED = "ranged"
    MAGICAL = "magical"
    SUPPORT = "support"


class PersonalityTrait(str, Enum):
    """Personality traits that influence mob behavior."""

    FRIENDLY = "friendly"
    HOSTILE = "hostile"
    CURIOUS = "curious"
    GREEDY = "greedy"
    PROUD = "proud"
    CUNNING = "cunning"
    NOBLE = "noble"
    SAVAGE = "savage"
    MYSTERIOUS = "mysterious"
    PLAYFUL = "playful"
    MELANCHOLIC = "melancholic"
    WISE = "wise"


class MobPersonality(BaseModel):
    """Personality profile for a mob, influencing combat and dialogue."""

    traits: list[PersonalityTrait] = Field(
        min_length=1,
        max_length=3,
        description="Primary personality traits",
    )
    combat_style: CombatStyle = Field(description="How the mob approaches combat")
    flee_threshold: float = Field(
        ge=0.0,
        le=1.0,
        default=0.2,
        description="Health percentage at which mob considers fleeing (0-1)",
    )
    dialogue_style: str = Field(
        max_length=100,
        description="Brief description of how this mob speaks",
    )
    motivations: list[str] = Field(
        default_factory=list,
        max_length=3,
        description="What drives this mob's behavior",
    )
    fears: list[str] = Field(
        default_factory=list,
        max_length=3,
        description="What this mob is afraid of",
    )


class MobAbility(BaseModel):
    """A special ability a mob can use."""

    name: str = Field(max_length=30, description="Name of the ability")
    description: str = Field(max_length=200, description="What the ability does")
    damage_type: Optional[str] = Field(default=None, description="Type of damage if applicable")
    cooldown_rounds: int = Field(ge=0, default=3, description="Rounds between uses")


class GeneratedMob(BaseModel):
    """Schema for LLM-generated mob content."""

    name: str = Field(
        min_length=2,
        max_length=40,
        description="Name of the mob (e.g., 'a goblin scout')",
    )
    keywords: list[str] = Field(
        min_length=1,
        max_length=5,
        description="Keywords players can use to target this mob",
    )
    short_description: str = Field(
        min_length=10,
        max_length=80,
        description="Description shown in room (e.g., 'A goblin scout lurks here.')",
    )
    long_description: str = Field(
        min_length=50,
        max_length=500,
        description="Full description when looking at the mob",
    )
    level: int = Field(ge=1, le=100, description="Challenge level of the mob")
    health: int = Field(ge=1, description="Maximum hit points")
    mana: int = Field(ge=0, default=0, description="Maximum mana points")
    personality: MobPersonality = Field(description="Personality profile")
    abilities: list[MobAbility] = Field(
        default_factory=list,
        max_length=4,
        description="Special abilities the mob can use",
    )
    damage_dice: str = Field(
        default="1d6",
        pattern=r"^\d+d\d+(\+\d+)?$",
        description="Damage dice (e.g., '2d6+3')",
    )
    damage_type: str = Field(default="bludgeoning", description="Type of damage dealt")
    armor_class: int = Field(ge=0, le=30, default=10, description="Armor class")
    backstory: Optional[str] = Field(
        default=None,
        max_length=300,
        description="Brief backstory for this mob",
    )


class ItemRarity(str, Enum):
    """Item rarity levels."""

    COMMON = "common"
    UNCOMMON = "uncommon"
    RARE = "rare"
    EPIC = "epic"
    LEGENDARY = "legendary"


class ItemType(str, Enum):
    """Types of items."""

    WEAPON = "weapon"
    ARMOR = "armor"
    CONSUMABLE = "consumable"
    CONTAINER = "container"
    KEY = "key"
    TREASURE = "treasure"
    MISC = "misc"
    QUEST = "quest"


class EquipmentSlot(str, Enum):
    """Equipment slots for wearable items."""

    HEAD = "head"
    NECK = "neck"
    SHOULDERS = "shoulders"
    CHEST = "chest"
    BACK = "back"
    ARMS = "arms"
    HANDS = "hands"
    WAIST = "waist"
    LEGS = "legs"
    FEET = "feet"
    FINGER = "finger"
    WRIST = "wrist"
    MAIN_HAND = "main_hand"
    OFF_HAND = "off_hand"
    TWO_HAND = "two_hand"


class ItemEffect(BaseModel):
    """A magical effect on an item."""

    name: str = Field(max_length=30, description="Name of the effect")
    description: str = Field(max_length=100, description="What the effect does")
    stat_bonus: Optional[dict[str, int]] = Field(
        default=None, description="Stat bonuses (e.g., {'strength': 2})"
    )


class GeneratedItem(BaseModel):
    """Schema for LLM-generated item content."""

    name: str = Field(
        min_length=2,
        max_length=50,
        description="Name of the item (e.g., 'a gleaming shortsword')",
    )
    keywords: list[str] = Field(
        min_length=1,
        max_length=5,
        description="Keywords players can use to target this item",
    )
    short_description: str = Field(
        min_length=10,
        max_length=80,
        description="Description shown when item is on ground",
    )
    long_description: str = Field(
        min_length=30,
        max_length=400,
        description="Full description when looking at the item",
    )
    item_type: ItemType = Field(description="Type of item")
    rarity: ItemRarity = Field(default=ItemRarity.COMMON, description="Rarity level")
    level_requirement: int = Field(ge=0, default=0, description="Level required to use")
    weight: float = Field(ge=0.0, default=1.0, description="Weight in pounds")
    value: int = Field(ge=0, default=0, description="Base gold value")
    equipment_slot: Optional[EquipmentSlot] = Field(
        default=None, description="Equipment slot if wearable/wieldable"
    )
    damage_dice: Optional[str] = Field(
        default=None,
        pattern=r"^\d+d\d+(\+\d+)?$",
        description="Damage dice if weapon",
    )
    damage_type: Optional[str] = Field(default=None, description="Damage type if weapon")
    armor_bonus: Optional[int] = Field(default=None, ge=0, description="Armor bonus if armor")
    effects: list[ItemEffect] = Field(
        default_factory=list,
        max_length=3,
        description="Magical effects on the item",
    )
    lore: Optional[str] = Field(
        default=None,
        max_length=300,
        description="Lore/history of this item",
    )


class DialogueTopic(BaseModel):
    """A dialogue topic for a mob."""

    keyword: str = Field(max_length=20, description="Keyword to trigger this topic")
    response: str = Field(max_length=500, description="The mob's response")


class GeneratedDialogue(BaseModel):
    """Schema for LLM-generated dialogue content."""

    greeting: str = Field(
        min_length=10,
        max_length=300,
        description="Initial greeting when player talks to mob",
    )
    farewell: str = Field(
        min_length=5,
        max_length=100,
        description="Response when player ends conversation",
    )
    topics: list[DialogueTopic] = Field(
        default_factory=list,
        max_length=10,
        description="Dialogue topics the player can ask about",
    )
    combat_taunt: Optional[str] = Field(
        default=None,
        max_length=100,
        description="What the mob says when entering combat",
    )
    combat_victory: Optional[str] = Field(
        default=None,
        max_length=100,
        description="What the mob says when defeating a player",
    )
    combat_flee: Optional[str] = Field(
        default=None,
        max_length=100,
        description="What the mob says when fleeing",
    )
